version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/flashlight:8.1.0-8.1 # Latest stable version of the PrestaShop, to see all available images go to ...
    volumes:
      - ./init-scripts:/tmp/init-scripts:ro
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    networks:
      - prestashop_network
networks:
  prestashop_network: